-- https://leetcode.com/problems/restaurant-growth

WITH cte AS (
	SELECT visited_on, SUM(amount) AS days_sum
	FROM customer
	GROUP BY visited_on
	ORDER BY visited_on
)

SELECT 
	visited_on,
	SUM(days_sum) OVER(ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS amount,
	ROUND(AVG(days_sum) OVER(ROWS BETWEEN 6 PRECEDING AND CURRENT ROW), 2) AS average_amount
FROM cte 
OFFSET 6

-- SUM(column1) OVER(ORDER BY column2 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
-- SUM(column1) OVER(ORDER BY column2 ROWS BETWEEN N PRECEDING AND CURRENT ROW)
-- SUM(column1) OVER(ORDER BY column2 ROWS BETWEEN N PRECEDING)

-- SUM(column1) OVER(ORDER BY column2 ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING)
-- SUM(column1) OVER(ORDER BY column2 ROWS BETWEEN CURRENT ROW AND N FOLLOWING)

-- SUM(column1) OVER(ORDER BY column2 ROWS BETWEEN N PRECEDING AND N FOLLOWING)